// RenderLinks.js
export const frontendToBackendKey = {
  'Chart of Accounts': 'chart_of_account',
  'Party Ledger': 'party_ledger',
  'WIC Register': 'walk_in_customer',
  'Teller Register': 'teller_register',
  'Classification Register': 'classification_register',
  'Warehouse Register': 'warehouse_register',
  'CB Classification Register': 'cb_classification_register',
  'Beneficiary Register': 'beneficiary_register',
  'Document Register': 'document_register',
  'Salesman Register': 'salesman_register',
  'Commission Register': 'commission_register',
  'Currency Register': 'currency_register',
  'Country Register': 'country_register',
  'Office Location Register': 'office_location_register',
  'Cost Center Register': 'cost_center_register',
  'Group Register': 'group_register',
  'Journal Voucher': 'journal_voucher',
  'Receipt Voucher': 'receipt_voucher',
  'Payment Voucher': 'payment_voucher',
  'Internal Payment Voucher': 'internal_payment_voucher',
  'Bank Transactions': 'bank_transactions',
  'Account to Account': 'account_to_account',
  'PDCR Payment Voucher': 'pdcr_payment_voucher',
  'Suspense Voucher': 'suspense_voucher',
  'Suspense Posting': 'suspense_posting',
  'Foreign Currency Deal': 'foreign_currency_deal',
  'TMN Currency Deal': 'tmn_currency_deal',
  'Currency Transfer Request': 'currency_transfer',
  'Deal Register': 'deal_register',
  'TTR Register': 'ttr_register',
  'Outward Remittance': 'outward_remittance',
  'Outward Remittance Register': 'outward_remittance_register',
  'Application Printing': 'application_printing',
  'Inward Payment Order': 'inward_payment_order',
  'Inward Payment': 'inward_payment',
  'Inward Payment Cancellation': 'inward_payment_cancellation',
  'Rate of Exchange': 'rate_of_exchange',
  'P.D.C Process': 'pdc_process',
  'PDCR Payment Posting': 'pdc_payment_processing',
  'Profit & Loss Posting': 'profit_loss_posting',
  'Periodic Accounts Locking': 'periodic_account_locking',
  'Balance Write-off': 'balance_write_off',
  'Transaction Approval': 'transaction_approval',
  'Transaction Lock': 'transaction_lock_register',
  'Budget Setup': 'budget_setup',
  'Accounting Reports': 'journal_report',
  'Statement of Accounts': 'statement_of_account',
  'Outstanding Balance Report': 'outstanding_balance',
  'Journal Report': 'journal_report',
  'WIC Statement': 'walk_in_customer_statement',
  'WIC Outstanding Balance Report': 'walk_in_customer_outstanding_balance',
  'Expense Journal': 'expense_journal',
  'Post Dated Cheques Report': 'post_dated_cheque_report',
  'Account Enquiry': 'account_enquiry',
  'Account Turnover Report': 'account_turnover_report',
  'VAT Report': 'vat_report',
  'Inward Remittance Report': 'inward_remittance_report',
  'Outward Remittance Report': 'outward_remittance_report',
  'TRQ Report': 'currency_transfer_register_report',
  'Deal Register Report': 'deal_register_report',
  'Outward Remittance Enquiry': 'outward_remittance_enquiry',
  'Trial Balance': 'trial_balance',
  'Profit & Loss Statement': 'profit_loss_statement',
  'Balance Sheet': 'balance_sheet',
  'Exchange Profit & Loss Report': 'exchange_profit_loss',
  'Cash & Bank Balance Position': 'cash_bank_balance',
  'Budgeting Report': 'budgeting_forecasting_report',
  'User Maintenance': 'user_maintenance',
  'Cheque Register': 'cheque_register',
  'System Integrity Check': 'system_integrity_check',
  'Deal Register Updation': 'deal_register_updation',
  'Subscription Logs': 'subscription_logs',
  'Password Reset': 'password_reset',
  'Transaction Number Register': 'transaction_number_register',
  'Branch Management': 'branch_management',
  'Branch Selection': 'branch_selection',
  'Maturity Alert': 'maturity_alert',
  'Transaction Logs': 'transaction_log',
  'User Logs': 'user_logs',
  'Unlock Request Logs': 'unlock_request_logs',
};